### ISSUE TITLE
Create the Board

### ISSUE THREAD

**Issue by tine-krueger** [tine-krueger/connect-four#2]
## Value statement - a requirement, not a solution
As a user
I need to see a board
so that I can start the game
## Acceptance criteria
- [x] Board 7 columns x 6 rows
## Tasks
- [x] State with useReducer
- [x] Initial State as Array with 7 column-arrays with 6 elements
- [x] Mapping of arrays to visualize Board
- [x] columns arrays have to be ordered vertically, elements in the arrays have to be arranged horizontally
## Size
medium
