### ISSUE TITLE
reducer column click

### ISSUE THREAD

**Issue by tine-krueger** [tine-krueger/connect-four#7]
## Value statement - a requirement, not a solution
As a player
I need to click a column
so that my round number is displayed at the first free row from bottom
## Acceptance criteria
- [ ] 0 in clicked column changes to 1 or 2 regarding the number of the round
## Tasks
- [ ] write a counter
- [ ] write a find function for the first zero in column-array
- [ ] change 0 to 1 or 2 depending on (even or odd) counter output
## Size
 medium
